### ISSUE TITLE
limu在react useState的更新中作为新值传递无效,额外的useState触发更新后才触发视图更新

### ISSUE THREAD

**Issue by itmanyong** [tnfe/limu#1]
如图所示：useLimu的更新不起作用,且在非useLimu的更新触发更新后,useLimu之前的更新才会在视图上呈现最新的值
![image](https://user-images.githubusercontent.com/53500371/123791592-39f61780-d912-11eb-8620-d10b86ef339c.png)

**Comment by fantasticsoul** [comment]
fixed in `1.09`
