### ISSUE TITLE
limu的array.forEach方法貌似未生效???!!

### ISSUE THREAD

**Issue by itmanyong** [tnfe/limu#2]
![image](https://user-images.githubusercontent.com/53500371/126140150-a2121c40-3846-4edb-9b62-54741a7c9930.png)

复现链接：
https://codesandbox.io/s/lucid-water-nct7x

难道是因为limu外层引用未变，react的更新检查策略未到深层变化？

**Comment by fantasticsoul** [comment]
升级到 1.0.11, bug已fix，感谢关注

**Comment by itmanyong** [comment]
不知道是不是用法问题，sandbox中升级1.0.11后仍然未生效，甚至count的变化也不能触发被produce的数据更新视图

**Comment by itmanyong** [comment]
> ![图像](https://user-images.githubusercontent.com/53500371/126140150-a2121c40-3846-4edb-9b62-54741a7c9930.png)
> 
> 复现链接：
> https://codesandbox.io/s/lucid-water-nct7x
> 
> 难道是因为limu外层引用未变，反应的更新检查策略未到变化？
不知道是不是最合适的问题，沙箱中升级1.0.11后仍然未生效，甚至计算的变化也不能触发被产生的数据更新视图

**Comment by itmanyong** [comment]
> 升级到1.0.11，bug已修复，感谢关注

不知道是不是最合适的问题，沙箱中升级1.0.11后仍然未生效，甚至计算的变化也不能触发被产生的数据更新视图

**Comment by fantasticsoul** [comment]
遗漏了一个场景已fix，更新到 1.0.12即可，同时推荐把代码改为如下格式，更方便测试
```ts
o.name = "王二麻子" + Date.now();
```

同时更新了测试用例
https://github.com/tnfe/limu/blob/main/test/array-other/object-item-3.ts

欢迎fork源码补充，更多测试用例

**Comment by itmanyong** [comment]
> 遗漏了一个场景已修复，更新到1.0.12目录，同时推荐把代码改为格式，更方便测试
> 
> ```ts
> 哦。name  =  "王二麻子"  +  Date . 现在( ) ;
> ```
> 
> 同时更新了测试用例
> https://github.com/tnfe/limu/blob/main/test/array-other/object-item-3.ts
> 
> 欢迎fork源码，补充更多测试用例

如果是批量更新有更好的方式吗

**Comment by itmanyong** [comment]
> 遗漏了一个场景已修复，更新到1.0.12目录，同时推荐把代码改为格式，更方便测试
> 
> ```ts
> 哦。name  =  "王二麻子"  +  Date .现在( ) ;
> ```
> 
> 同时更新了测试用例
> https://github.com/tnfe/limu/blob/main/test/array-other/object-item-3.ts
> 
> 欢迎fork源码，补充更多测试用例

主要是为了批量更新,感谢！早已fork

**Comment by fantasticsoul** [comment]
好的，😀

**Comment by fantasticsoul** [comment]
欢迎发现更多的问题，我努力争取早日发布稳定版本 1.1.0

**Comment by itmanyong** [comment]
> 欢迎发现更多的问题，我努力争取早日发布稳定版本 1.1.0

打包后的数据修改日志还在~~~

**Comment by fantasticsoul** [comment]
好的我把多余的日志关掉

**Comment by fantasticsoul** [comment]
还麻烦更新到1.0.13哈，fix了嵌套对象更新的问题，test用例如下

https://github.com/tnfe/limu/blob/main/test/array-other/object-item-nested.ts
https://github.com/tnfe/limu/blob/main/test/map-other/case-nested-object.ts
