### ISSUE TITLE
支持promise返回值

### ISSUE THREAD

**Issue by geekact** [tnfe/limu#5]
根据源码，limu判断produce的回调是否异步是通过`isPromiseFn`来判断。这只能支持`async function() {}`的写法，因此未考虑到用户写的是普通函数，最后返回的却是Promise实例的场景。
```typescript
const result = produce(obj, (draft) => {
  return Promise.resolve().then(...);
});
```
因此建议参考immer https://github.com/immerjs/immer/blob/master/src/core/immerClass.ts#L101 ，替换掉`isPromiseFn`

**Comment by fantasticsoul** [comment]
收到建议，感谢你的反馈，修复后会在此在此答复

**Comment by fantasticsoul** [comment]
已支持，见版本`1.3.0`
